#!/usr/bin/env python3
"""Emit frozen dataclasses from schemas/mhf/*.schema.json into
vanguard/packages/domain/wire/types_gen.py -- the sole canonical target
(Wave-2 2.1-B). `layer0/spi/types_gen.py` was a re-export shim for `layer0/`
consumers; 2.2-B rewrote every one of them onto this module directly and
deleted the shim, so this generator no longer writes a second file."""

from __future__ import annotations

import argparse
import json
import keyword
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent.parent
_COMMON = _TOOLS / "common"
for _path in (_COMMON, _TOOLS):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))

from repo_paths import repo_root

HEADER = '''\
# AUTO-GENERATED by tools/codegen/generate_types.py from schemas/mhf/*.schema.json.
# DO NOT EDIT. Run: python3 tools/codegen/generate_types.py
"""Generated MHF wire types. Hand-written mirrors are banned (SPEC A-4)."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping

JsonObject = Mapping[str, object]
ResourceSelector = Mapping[str, object]
Digest = str
MemoryId = str
EvaluationRequestId = str
PreregistrationId = str

'''

SKIP_DEFS = {
    "JsonObject",
    "ResourceSelector",
    "Digest",
    "MemoryId",
    "EvaluationRequestId",
    "PreregistrationId",
    "SpiPayloads",
}


def _load_schemas(schema_dir: Path) -> list[dict]:
    schemas: list[dict] = []
    for path in sorted(schema_dir.glob("*.schema.json")):
        payload = json.loads(path.read_text(encoding="utf-8"))
        payload["_path"] = path.name
        schemas.append(payload)
    return schemas


def _collect_defs(schemas: list[dict]) -> tuple[dict[str, dict], dict[str, str]]:
    """Definitions, plus the title of the document each one came from.

    `"$ref": "#"` means *the root of the document the ref appears in* (JSON
    Schema core). Resolving it against a single global root title made the
    generated types depend on which schema file happened to sort first: adding
    `artifact_created.schema.json` silently retyped `Proposal.requests` from
    `EffectRequest` to `ArtifactCreatedPayload`, and `--check` passed because
    the generator agreed with itself. Owning documents are tracked here so the
    resolution is document-relative, as the spec says it is.
    """
    defs: dict[str, dict] = {}
    roots: dict[str, str] = {}
    for schema in schemas:
        title = schema.get("title")
        if title and schema.get("type") == "object" and title not in SKIP_DEFS:
            defs[title] = schema
            roots[title] = title
        for name, body in schema.get("$defs", {}).items():
            if name in SKIP_DEFS:
                continue
            if name in defs and defs[name] != body:
                # Silent last-writer-wins across documents is how a stale copy
                # of a shared vocabulary quietly replaces the live one: the
                # generator would emit the loser's definition and `--check`
                # would agree with itself about it. Shared definitions belong
                # to exactly one document and are `$ref`d from the others.
                raise SystemExit(
                    f"CODEGEN FAIL: '{name}' is defined differently in "
                    f"{roots.get(name)!r} and {title!r}; $ref the owning "
                    "document instead of copying the definition")
            defs[name] = body
            if title:
                roots.setdefault(name, title)
    return defs, roots


def _ref_name(ref: str, *, root_title: str | None = None) -> str:
    if ref in ("#", "#/"):
        return root_title or "object"
    tail = ref.rsplit("/", 1)[-1]
    if tail == "#":
        return root_title or "object"
    return tail


def _py_type(
    node: dict,
    defs: dict[str, dict],
    *,
    root_title: str | None = None,
) -> str:
    if "$ref" in node:
        name = _ref_name(node["$ref"], root_title=root_title)
        if name in SKIP_DEFS:
            return {
                "JsonObject": "JsonObject",
                "ResourceSelector": "ResourceSelector",
                "Digest": "Digest",
                "MemoryId": "MemoryId",
                "EvaluationRequestId": "EvaluationRequestId",
                "PreregistrationId": "PreregistrationId",
            }[name]
        target = defs.get(name, {})
        if target.get("enum") and target.get("type") == "string":
            return name
        if target.get("type") == "object":
            return name
        if target.get("type") == "string":
            return "str"
        return name
    if "anyOf" in node:
        parts = [_py_type(option, defs, root_title=root_title) for option in node["anyOf"]]
        return " | ".join(parts)
    types = node.get("type")
    if isinstance(types, list):
        mapped = []
        for item in types:
            if item == "null":
                mapped.append("None")
            else:
                mapped.append(_py_type({**node, "type": item}, defs, root_title=root_title))
        return " | ".join(mapped)
    if types == "string":
        if node.get("enum"):
            return "str"
        return "str"
    if types == "integer":
        return "int"
    if types == "number":
        return "float"
    if types == "boolean":
        return "bool"
    if types == "object":
        return "JsonObject"
    if types == "array":
        inner = _py_type(node.get("items", {"type": "object"}), defs, root_title=root_title)
        return f"tuple[{inner}, ...]"
    return "object"


def _is_enum(node: dict) -> bool:
    return node.get("type") == "string" and bool(node.get("enum"))


def _is_object(node: dict) -> bool:
    return node.get("type") == "object" and "properties" in node


def _enum_block(name: str, node: dict) -> str:
    lines = [f"class {name}(str, Enum):"]
    for value in node["enum"]:
        ident = value.replace("-", "_")
        if ident.isupper() or ident.replace("_", "").isupper():
            member = ident
        else:
            member = "".join(
                part.upper() if part.isupper() else part
                for part in _snake_member(value)
            )
            member = _snake_member(value).upper()
        lines.append(f'    {member} = "{value}"')
    return "\n".join(lines) + "\n"


def _snake_member(value: str) -> str:
    chars: list[str] = []
    for index, char in enumerate(value):
        if char.isupper() and index and (value[index - 1].islower() or (
            index + 1 < len(value) and value[index + 1].islower()
        )):
            chars.append("_")
        chars.append(char)
    return "".join(chars).replace("-", "_")


def _dataclass_block(
    name: str,
    node: dict,
    defs: dict[str, dict],
    *,
    root_title: str | None = None,
) -> str:
    required = list(node.get("required", []))
    properties: dict[str, dict] = dict(node.get("properties", {}))
    ordered = [key for key in required if key in properties]
    ordered.extend(key for key in properties if key not in ordered)
    lines = ["@dataclass(frozen=True, slots=True)", f"class {name}:"]
    if not ordered:
        lines.append("    pass")
        return "\n".join(lines) + "\n"
    for key in ordered:
        prop = properties[key]
        field_name = f"{key}_" if keyword.iskeyword(key) else key
        annotation = _py_type(prop, defs, root_title=root_title)
        if key in required and "default" not in prop:
            lines.append(f"    {field_name}: {annotation}")
            continue
        default = prop.get("default", None)
        if annotation.startswith("tuple["):
            lines.append(
                f"    {field_name}: {annotation} = field(default_factory=tuple)"
            )
        elif annotation == "JsonObject":
            lines.append(
                f"    {field_name}: {annotation} = field(default_factory=dict)"
            )
        elif default is None:
            if not annotation.endswith("| None") and "None" not in annotation.split():
                annotation = f"{annotation} | None"
            lines.append(f"    {field_name}: {annotation} = None")
        elif isinstance(default, bool):
            lines.append(f"    {field_name}: {annotation} = {default!s}")
        elif isinstance(default, str):
            lines.append(f"    {field_name}: {annotation} = {default!r}")
        elif isinstance(default, (int, float)):
            lines.append(f"    {field_name}: {annotation} = {default!r}")
        else:
            lines.append(f"    {field_name}: {annotation} = None")
    if name == "Reservation":
        lines.append("")
        lines.append("    def as_map(self) -> Mapping[str, int]:")
        lines.append(
            '        return {"usd_micros": self.usd_micros, "millis": self.millis,'
        )
        lines.append(
            '                "tokens": self.tokens, "bytes": self.bytes,'
        )
        lines.append(
            '                "turns": self.turns, "depth": self.depth}'
        )
    return "\n".join(lines) + "\n"


def _topo(defs: dict[str, dict], *, roots: dict[str, str],
          root_title: str | None = None) -> list[str]:
    enums = [name for name, node in defs.items() if _is_enum(node)]
    objects = [name for name, node in defs.items() if _is_object(node)]
    remaining = set(objects)
    ordered: list[str] = []
    while remaining:
        progress = False
        for name in sorted(remaining):
            deps = _object_deps(defs[name], defs,
                                root_title=roots.get(name, root_title))
            if deps <= (set(ordered) | set(enums) | SKIP_DEFS):
                ordered.append(name)
                remaining.remove(name)
                progress = True
        if not progress:
            ordered.extend(sorted(remaining))
            break
    return enums + ordered


def _object_deps(
    node: dict,
    defs: dict[str, dict],
    *,
    root_title: str | None = None,
) -> set[str]:
    deps: set[str] = set()

    def walk(item: dict) -> None:
        if "$ref" in item:
            deps.add(_ref_name(item["$ref"], root_title=root_title))
            return
        if "anyOf" in item:
            for option in item["anyOf"]:
                walk(option)
        if item.get("type") == "array" and "items" in item:
            walk(item["items"])
        for prop in item.get("properties", {}).values():
            walk(prop)

    walk(node)
    return {name for name in deps if name in defs}


def render(schema_dir: Path) -> str:
    schemas = _load_schemas(schema_dir)
    defs, roots = _collect_defs(schemas)
    root_title = next(
        (schema.get("title") for schema in schemas if schema.get("title")),
        "object",
    )
    chunks = [HEADER]
    exported: list[str] = [
        "JsonObject", "ResourceSelector", "Digest", "MemoryId",
        "EvaluationRequestId", "PreregistrationId",
    ]
    for name in _topo(defs, roots=roots, root_title=root_title):
        node = defs[name]
        if _is_enum(node):
            chunks.append(_enum_block(name, node))
            exported.append(name)
        elif _is_object(node):
            chunks.append(_dataclass_block(name, node, defs,
                                           root_title=roots.get(name, root_title)))
            exported.append(name)
    chunks.append("__all__ = [")
    for name in exported:
        chunks.append(f'    "{name}",')
    chunks.append("]")
    chunks.append("")
    return "\n".join(chunks)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    root = repo_root()
    schema_dir = root / "schemas" / "mhf"
    out_path = root / "vanguard" / "packages" / "domain" / "wire" / "types_gen.py"
    text = render(schema_dir)
    if args.check:
        current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        if current != text:
            print(f"CODEGEN FAIL: {out_path.relative_to(root)} stale; run tools/codegen/generate_types.py")
            return 1
        print("CODEGEN PASS: types_gen.py matches schemas/mhf")
        return 0
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    print(f"wrote {out_path.relative_to(root)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
