import { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { ReplayRuntimeClient, emptyRunView, reduceRunView, type EventEnvelope, type RunViewModel } from "@vanguard/client-core";
import { FilesSlot, SlotFrame, type WorkspaceFile } from "./slots/files";
import { EditorSlot } from "./slots/editor";
import { TerminalSlot } from "./slots/terminal";
import "./style.css";

type SlotId = "files" | "editor" | "terminal" | "run" | "trace-canvas" | "approve";
const slots: SlotId[] = ["files", "editor", "terminal", "run", "trace-canvas", "approve"];

function RunSlot({ view, events }: { view: RunViewModel; events: EventEnvelope[] }) { const windowed = events.slice(-100); return <SlotFrame title="RUN / REPLAY"><div className="badge">source: mock · replay fixture</div><div className="metrics"><div><b>{view.tokens}</b><small>TOKENS</small></div><div><b>{view.costMicros}</b><small>COST (μ)</small></div><div><b>{view.lastKind || "—"}</b><small>LAST EVENT</small></div></div><div className="stream">{windowed.map(event => <div className="event" key={event.eventId}><span>{event.seq}</span><code>{event.payload.kind}</code><em>{String(event.payload.text ?? event.payload.tool ?? event.payload.state ?? event.payload.outcome ?? "ledger event")}</em></div>)}</div><div className="subgrid"><div><h4>THOUGHTS</h4>{view.thoughts.length ? view.thoughts.map((x, i) => <p key={i}>{x}</p>) : <p className="muted">No ObservationProduced events in this fixture.</p>}</div><div><h4>TOOLS</h4>{view.tools.length ? view.tools.map((x, i) => <p key={i}><code>{x.name}</code> {x.status}</p>) : <p className="muted">No OperatorInvoked events in this fixture.</p>}</div></div></SlotFrame>; }

function App() {
  const [view, setView] = useState(emptyRunView()); const [events, setEvents] = useState<EventEnvelope[]>([]); const [active, setActive] = useState<SlotId>("run"); const [file, setFile] = useState<WorkspaceFile>();
  useEffect(() => { fetch("/successful-episode.jsonl").then(response => response.text()).then(async text => { const client = ReplayRuntimeClient.fromJsonl(text, "mock"); const ref = await client.startRun({ repo: "." }); if (!ref.ok) return; let next = emptyRunView(); const windowed: EventEnvelope[] = []; for await (const item of client.streamEvents({ runId: ref.value.runId })) if (item.ok) { windowed.push(item.value.envelope); if (windowed.length > 100) windowed.shift(); next = reduceRunView(next, item.value.envelope); } setEvents(windowed); setView(next); }); }, []);
  const content = useMemo(() => { switch (active) { case "files": return <SlotFrame title="WORKSPACE FILES"><FilesSlot onOpen={selected => { setFile(selected); setActive("editor"); }} /></SlotFrame>; case "editor": return <EditorSlot file={file} />; case "terminal": return <TerminalSlot />; case "run": return <RunSlot view={view} events={events} />; case "trace-canvas": return <SlotFrame title="VG-04 EVENT VISUALIZER"><div className="canvas">{events.slice(-12).map((event, i) => <div className="node" key={event.eventId} style={{ left: `${8 + (i % 3) * 30}%`, top: `${20 + Math.floor(i / 3) * 35}%` }}><b>{event.payload.kind}</b><small>seq {event.seq}</small></div>)}</div><p className="muted">Passive visualizer placeholder; xyflow binding is Wave 3.</p></SlotFrame>; case "approve": return <SlotFrame title="DIFF / APPROVE"><div className="diff">No ApprovalRequested envelope in this replay.</div><p className="muted">Approval actions remain Wave 3.</p></SlotFrame>; } }, [active, events, file, view]);
  return <main><header><div><span className="logo">VG</span><strong>VANGUARD</strong><span className="crumb"> / standalone GUI</span></div><span className="status">● OFFLINE REPLAY</span></header><nav>{slots.map(slot => <button className={active === slot ? "active" : ""} onClick={() => setActive(slot)} key={slot}>{slot.replace("-", " ")}</button>)}</nav><div className="workspace"><aside><h3>SLOTS</h3>{slots.map(slot => <button className={active === slot ? "selected" : ""} onClick={() => setActive(slot)} key={slot}>◼ {slot}</button>)}</aside><div className="content">{content}</div></div><footer>VG-04 · client-core · fixture: successful-episode.jsonl</footer></main>;
}
createRoot(document.getElementById("root")!).render(<App />);
