# AUTO-GENERATED by tools/codegen/generate_types.py.
# DO NOT EDIT. Wave-2 (2.1-B) compatibility shim: the canonical generated
# types live at vanguard/packages/domain/wire/types_gen.py. This re-export
# keeps layer0/ importing unmodified until 2.2-B deletes layer0/ entirely --
# it is not a second generator, only a redirect to the one canonical target.
"""Re-export of the canonical generated MHF wire types.

See vanguard/packages/domain/wire/types_gen.py -- the only place these
dataclasses are defined (SPEC A-4).
"""

from __future__ import annotations

from vanguard.packages.domain.wire.types_gen import *  # noqa: F401,F403
from vanguard.packages.domain.wire.types_gen import __all__
