# AUTO-GENERATED by tools/codegen/generate_types.py from schemas/mhf/*.schema.json.
# DO NOT EDIT. Run: python3 tools/codegen/generate_types.py
"""Generated MHF wire types. Hand-written mirrors are banned (SPEC A-4)."""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Mapping

JsonObject = Mapping[str, object]
ResourceSelector = Mapping[str, object]
Digest = str
MemoryId = str
EvaluationRequestId = str
PreregistrationId = str


class SinkClass(str, Enum):
    OBSERVATION = "observation"
    ADVISORY = "advisory"
    PRIVILEGED = "privileged"

class EventKind(str, Enum):
    RUN_STARTED = "RunStarted"
    EPISODE_STARTED = "EpisodeStarted"
    TURN_STARTED = "TurnStarted"
    EPISODE_COMPLETED = "EpisodeCompleted"
    RUN_COMPLETED = "RunCompleted"
    RUN_ABORTED = "RunAborted"
    RUN_RECOVERED = "RunRecovered"
    PROPOSAL_PRODUCED = "ProposalProduced"
    PROPOSAL_REJECTED = "ProposalRejected"
    REFLECTION_PRODUCED = "ReflectionProduced"
    AUTHORIZATION_REQUESTED = "AuthorizationRequested"
    AUTHORIZATION_DENIED = "AuthorizationDenied"
    CAPABILITY_GRANTED = "CapabilityGranted"
    CAPABILITY_ATTENUATED = "CapabilityAttenuated"
    CAPABILITY_REVOKED = "CapabilityRevoked"
    BUDGET_RESERVED = "BudgetReserved"
    BUDGET_COMMITTED = "BudgetCommitted"
    BUDGET_RELEASED = "BudgetReleased"
    BUDGET_EXHAUSTED = "BudgetExhausted"
    EFFECT_STARTED = "EffectStarted"
    EFFECT_COMPLETED = "EffectCompleted"
    EFFECT_FAILED = "EffectFailed"
    EFFECT_REJECTED = "EffectRejected"
    EFFECT_RECONCILED = "EffectReconciled"
    EVALUATION_REQUESTED = "EvaluationRequested"
    VERDICT_RECORDED = "VerdictRecorded"
    CLAIM_RECORDED = "ClaimRecorded"
    INVALIDATION_CHECKED = "InvalidationChecked"
    APPROVAL_REQUESTED = "ApprovalRequested"
    APPROVAL_RESOLVED = "ApprovalResolved"
    KERNEL_ALARM = "KernelAlarm"
    PLUGIN_DISCOVERED = "PluginDiscovered"
    PLUGIN_RESOLVED = "PluginResolved"
    PLUGIN_VERIFIED = "PluginVerified"
    PLUGIN_ACTIVATED = "PluginActivated"
    PLUGIN_QUIESCED = "PluginQuiesced"
    PLUGIN_RETIRED = "PluginRetired"
    PLUGIN_FAULTED = "PluginFaulted"
    HEARTBEAT = "Heartbeat"
    CHECKPOINT_CREATED = "CheckpointCreated"
    CHILD_SPAWNED = "ChildSpawned"
    CHILD_RETURNED = "ChildReturned"
    ACTIVATION_CHANGED = "ActivationChanged"
    ARTIFACT_CREATED = "ArtifactCreated"
    COMPETENCE_PRIOR_RECORDED = "CompetencePriorRecorded"
    CONFLICT_DETECTED = "ConflictDetected"
    EFFECT_PREVIEWED = "EffectPreviewed"
    EPISODE_STATE_CHANGED = "EpisodeStateChanged"
    EVIDENCE_CLAIM_PRODUCED = "EvidenceClaimProduced"
    OBSERVATION_PRODUCED = "ObservationProduced"
    OBSERVATION_REQUESTED = "ObservationRequested"
    OPERATOR_INVOKED = "OperatorInvoked"
    OPERATOR_SELECTED = "OperatorSelected"
    CORRECTION_RECORDED = "CorrectionRecorded"
    CANDIDATE_BUILT = "CandidateBuilt"
    CANDIDATE_ATTESTED = "CandidateAttested"
    CANARY_PROMOTED = "CanaryPromoted"
    ROLLBACK_TRIGGERED = "RollbackTriggered"
    GOAL_DECLARED = "GoalDeclared"
    PLAN_REVISED = "PlanRevised"
    STRATEGY_CHANGED = "StrategyChanged"
    PROGRESS_ASSESSED = "ProgressAssessed"
    CONTEXT_COMPACTED = "ContextCompacted"

class GateDecision(str, Enum):
    PASS = "PASS"
    RETRY = "RETRY"
    ESCALATE = "ESCALATE"
    ABANDON = "ABANDON"

@dataclass(frozen=True, slots=True)
class ArtifactCreatedPayload:
    artifactId: str
    digest: str
    role: str
    schemaId: str
    sizeBytes: int
    retentionClass: str
    stored: bool
    producedBy: JsonObject
    refs: JsonObject = field(default_factory=dict)

@dataclass(frozen=True, slots=True)
class ArtifactIndexEntry:
    artifactId: str
    digest: str
    role: str
    schemaId: str
    sizeBytes: int
    retentionClass: str
    stored: bool
    producedBy: JsonObject = field(default_factory=dict)
    refs: JsonObject = field(default_factory=dict)

@dataclass(frozen=True, slots=True)
class ArtifactRef:
    digest: Digest
    kind: str

@dataclass(frozen=True, slots=True)
class Binding:
    from_: str
    to: str
    interface: str | None = None
    relation: str | None = None
    channel: str | None = None
    lazy: bool | None = None

@dataclass(frozen=True, slots=True)
class BlobRef:
    digest: Digest
    media_type: str | None = None

@dataclass(frozen=True, slots=True)
class CheckpointPayload:
    projectionId: str
    reducerVersion: str
    schemaVersions: JsonObject
    stateDigest: str
    stateArtifact: str
    coveredThroughEventId: str
    coveredThroughSeq: str

@dataclass(frozen=True, slots=True)
class ClaimRef:
    claim_id: str

@dataclass(frozen=True, slots=True)
class CompactionReport:
    removed_tokens: int
    strategy: str | None = None

@dataclass(frozen=True, slots=True)
class ConsolidationReport:
    merged: int
    dropped: int

@dataclass(frozen=True, slots=True)
class ContextBundle:
    prefix: str
    suffix: str
    token_count: int | None = None

@dataclass(frozen=True, slots=True)
class ContextCompactedPayload:
    inputDigest: str
    outputDigest: str
    strategy: str | None = None
    tokensBefore: int | None = None
    tokensAfter: int | None = None
    removedTokens: int | None = None

@dataclass(frozen=True, slots=True)
class EffectContext:
    principal: str
    run_id: str
    episode_id: str | None = None
    depth: int | None = None
    parent_lease: str | None = None
    idempotency_key: str | None = None

@dataclass(frozen=True, slots=True)
class EffectFailure:
    verb: str
    detail: str

@dataclass(frozen=True, slots=True)
class EpisodeOutcome:
    status: str
    detail: str | None = None

@dataclass(frozen=True, slots=True)
class EpisodeView:
    run_id: str
    episode_id: str
    turn: int
    goal: str
    notes: str | None = None

@dataclass(frozen=True, slots=True)
class EvaluationSubject:
    run_id: str
    episode_id: str
    artifact_digest: str | None = None

@dataclass(frozen=True, slots=True)
class EventEnvelope:
    schema_version: str
    event_id: str
    kind: EventKind
    seq: int
    occurred_at: str
    run_id: str
    principal: str
    payload: JsonObject
    digest: str
    episode_id: str | None = None
    parent_episode_id: str | None = None
    project_id: str | None = None
    principal_id: str | None = None
    parent_principal_id: str | None = None
    harness_digest: str | None = None
    branch_id: str = 'main'
    prev_digest: str | None = None
    causation_id: str | None = None
    correlation_id: str | None = None
    idempotency_key: str | None = None
    alertable: bool = False

@dataclass(frozen=True, slots=True)
class EventEnvelopeV2:
    schema_version: str
    event_id: str
    kind: EventKind
    seq: int
    occurred_at: str
    run_id: str
    principal: str
    payload: JsonObject
    digest: str
    authority_source: str
    policy_version: str
    episode_id: str | None = None
    parent_episode_id: str | None = None
    project_id: str | None = None
    principal_id: str | None = None
    parent_principal_id: str | None = None
    harness_digest: str | None = None
    branch_id: str = 'main'
    prev_digest: str | None = None
    causation_id: str | None = None
    correlation_id: str | None = None
    idempotency_key: str | None = None
    alertable: bool = False
    approval_reference: str | None = None
    capability_grant: str | None = None

@dataclass(frozen=True, slots=True)
class ExecutionProfile:
    api: object
    id: str
    workspace: JsonObject
    process: JsonObject
    approval: JsonObject
    persistence: JsonObject
    evaluation: JsonObject
    assurance: JsonObject
    capture: JsonObject
    network: JsonObject = field(default_factory=dict)

@dataclass(frozen=True, slots=True)
class ExecutionProfileV2:
    api: object
    id: str
    workspace: JsonObject
    process: JsonObject
    approval: JsonObject
    persistence: JsonObject
    evaluation: JsonObject
    assurance: JsonObject
    retention: str
    capture: JsonObject
    network: JsonObject = field(default_factory=dict)

@dataclass(frozen=True, slots=True)
class GoalDeclaredPayload:
    goalDigest: str
    goalArtifact: str | None = None
    parentGoalDigest: str | None = None

@dataclass(frozen=True, slots=True)
class Health:
    ok: bool
    detail: str | None = None

@dataclass(frozen=True, slots=True)
class MeasurementStatus:
    status: str
    reason: str | None = None

@dataclass(frozen=True, slots=True)
class MemoryHit:
    id: str
    text: str
    score: float

@dataclass(frozen=True, slots=True)
class MemoryQuery:
    text: str
    kind: str | None = None
    limit: int | None = None

@dataclass(frozen=True, slots=True)
class MemoryRecord:
    kind: str
    text: str
    metadata: JsonObject = field(default_factory=dict)

@dataclass(frozen=True, slots=True)
class ModelRoute:
    tier: int
    provider: str
    model: str
    escalate_on: tuple[str, ...] = field(default_factory=tuple)

@dataclass(frozen=True, slots=True)
class OracleSpec:
    id: str
    digest: str | None = None

@dataclass(frozen=True, slots=True)
class PlanRevisedPayload:
    revision: int
    planDigest: str
    previousPlanDigest: str | None = None
    planArtifact: str | None = None
    rationaleDigest: str | None = None

@dataclass(frozen=True, slots=True)
class PluginRef:
    ref: str
    config: JsonObject = field(default_factory=dict)

@dataclass(frozen=True, slots=True)
class ProgressAssessedPayload:
    assessment: str
    signals: JsonObject
    basis: tuple[str, ...]
    confidence: float | None = None
    evidenceDigest: str | None = None

@dataclass(frozen=True, slots=True)
class ProvenanceClaimPayload:
    claimKind: str
    turnIndex: int
    policy: JsonObject = field(default_factory=dict)
    inputDigest: str | None = None
    outputDigest: str | None = None
    inputArtifacts: tuple[str, ...] = field(default_factory=tuple)
    outputArtifacts: tuple[str, ...] = field(default_factory=tuple)
    metrics: JsonObject = field(default_factory=dict)
    selectedLabels: tuple[str, ...] = field(default_factory=tuple)
    droppedLabels: tuple[str, ...] = field(default_factory=tuple)
    elidedLabels: tuple[str, ...] = field(default_factory=tuple)
    cacheId: str | None = None
    keyDigest: str | None = None
    sourceDigest: str | None = None
    hit: bool | None = None
    sourceStatus: str | None = None
    vector: JsonObject = field(default_factory=dict)
    basis: tuple[str, ...] = field(default_factory=tuple)
    reducerVersion: str | None = None
    schemaVersions: JsonObject = field(default_factory=dict)
    stateReconstructionReceipt: JsonObject = field(default_factory=dict)
    semanticReplayReceipt: JsonObject = field(default_factory=dict)

@dataclass(frozen=True, slots=True)
class Reflection:
    text: str

@dataclass(frozen=True, slots=True)
class Reservation:
    usd_micros: int
    millis: int
    tokens: int
    bytes: int
    turns: int
    depth: int

    def as_map(self) -> Mapping[str, int]:
        return {"usd_micros": self.usd_micros, "millis": self.millis,
                "tokens": self.tokens, "bytes": self.bytes,
                "turns": self.turns, "depth": self.depth}

@dataclass(frozen=True, slots=True)
class Selector:
    kind: object
    root: str | None = None
    paths: tuple[JsonObject, ...] = field(default_factory=tuple)
    uriPattern: str | None = None

@dataclass(frozen=True, slots=True)
class SignedVerdict:
    verdict: str
    signature: str
    subject_digest: str
    evaluation_request_id: str
    oracle_id: str
    nonce: str
    key_id: str
    signed_at: str

@dataclass(frozen=True, slots=True)
class StrategyChangedPayload:
    from_: str | None
    to: str
    trigger: str
    controllerId: str | None = None

@dataclass(frozen=True, slots=True)
class ToolSchema:
    verb: str
    schema: JsonObject

@dataclass(frozen=True, slots=True)
class TrajectoryRef:
    digest: str
    schema: str | None = None

@dataclass(frozen=True, slots=True)
class Capability:
    verb: str
    selector: Selector
    sink: object
    risk: str

@dataclass(frozen=True, slots=True)
class Component:
    config: object
    ceiling: tuple[Selector, ...]
    isolation: object
    interfaces: tuple[str, ...]
    kind: object | None = None
    spi: str | None = None
    role: str | None = None
    ref: str | None = None
    implementation: str | None = None
    entrypoints: tuple[str, ...] = field(default_factory=tuple)
    authority: bool | None = None

@dataclass(frozen=True, slots=True)
class CostVector:
    usd_micros: int
    tokens: int
    bytes: int
    millis: int
    measurement_status: JsonObject = field(default_factory=dict)

@dataclass(frozen=True, slots=True)
class EffectRequest:
    verb: str
    args: JsonObject
    selector: ResourceSelector
    sink: SinkClass
    reservation: Reservation

@dataclass(frozen=True, slots=True)
class FrozenHarness:
    api: str
    id: str
    digest: str
    resolved_refs: JsonObject
    budget: Reservation
    capability_ceiling: tuple[JsonObject, ...] = field(default_factory=tuple)
    undeletable: bool | None = None

@dataclass(frozen=True, slots=True)
class NamedManifestV2:
    api: object
    id: str
    components: JsonObject
    entrypoints: tuple[str, ...] | JsonObject
    bindings: tuple[Binding, ...] = field(default_factory=tuple)
    profiles: JsonObject = field(default_factory=dict)
    ceiling: tuple[Selector, ...] = field(default_factory=tuple)
    capabilities: tuple[Capability, ...] = field(default_factory=tuple)
    model_routes: tuple[JsonObject, ...] = field(default_factory=tuple)
    budget: JsonObject = field(default_factory=dict)
    system_prompt: str | None = None
    approval_policy: str | None = None
    guardrails: JsonObject = field(default_factory=dict)
    evaluation: object | None = None
    undeletable: bool | None = None

@dataclass(frozen=True, slots=True)
class PluginBindings:
    planner: PluginRef | None = None
    context: PluginRef | None = None
    memory: PluginRef | None = None
    toolkits: tuple[PluginRef, ...] = field(default_factory=tuple)
    evaluation: PluginRef | None = None
    model_routes: tuple[ModelRoute, ...] = field(default_factory=tuple)

@dataclass(frozen=True, slots=True)
class Proposal:
    requests: tuple[EffectRequest, ...]
    thought: str | None = None
    independence_groups: tuple[tuple[int, ...], ...] = field(default_factory=tuple)
    confidence: float | None = None

@dataclass(frozen=True, slots=True)
class Receipt:
    request_digest: Digest
    outcome: str
    cost: Reservation
    stdout_ref: BlobRef | object | None = None
    artifacts: tuple[ArtifactRef, ...] = field(default_factory=tuple)

@dataclass(frozen=True, slots=True)
class TrajectoryTurn:
    turn: int
    context_digest: str
    proposal: JsonObject
    receipts: tuple[JsonObject, ...]
    cost: CostVector
    context_ref: str | None = None
    model_route: JsonObject = field(default_factory=dict)
    invocations: tuple[JsonObject, ...] = field(default_factory=tuple)

@dataclass(frozen=True, slots=True)
class TrajectoryTurnV2:
    turn: int
    context_digest: str
    proposal: JsonObject
    receipts: tuple[JsonObject, ...]
    cost: CostVector
    context_ref: str | None = None
    model_route: JsonObject = field(default_factory=dict)
    invocations: tuple[JsonObject, ...] = field(default_factory=tuple)
    model_input_ref: str | None = None
    model_output_ref: str | None = None

@dataclass(frozen=True, slots=True)
class TrajectoryV2:
    schema: str
    project_id: str
    run_id: str
    episode_id: str
    principal_id: str
    harness_digest: str
    turns: tuple[TrajectoryTurnV2, ...]
    verdict: JsonObject | None
    cost: CostVector
    artifacts: tuple[ArtifactIndexEntry, ...]
    provenance: JsonObject
    reproducibility_at_run_close: JsonObject | None
    parent_episode_id: str | None = None
    execution_digest: str | None = None
    run_digest: str | None = None
    activation_digest: str | None = None
    task_digest: str | None = None
    preregistration_digest: str | None = None
    state_digest: str | None = None
    event_range: JsonObject | None = None
    manifest_genome: JsonObject = field(default_factory=dict)
    model_routes_used: tuple[JsonObject, ...] = field(default_factory=tuple)
    verdict_absence_reason: str | None = None
    attribution: JsonObject = field(default_factory=dict)
    outcome: str | None = None
    capture: JsonObject | None = None

@dataclass(frozen=True, slots=True)
class HarnessManifest:
    api: str
    id: str
    plugins: PluginBindings
    system_prompt: str | None = None
    capabilities: tuple[JsonObject, ...] = field(default_factory=tuple)
    budget: Reservation | None = None
    approval_policy: str | None = None
    undeletable: bool = False

@dataclass(frozen=True, slots=True)
class Trajectory:
    schema: str
    project_id: str
    run_id: str
    episode_id: str
    principal_id: str
    harness_digest: str
    turns: tuple[TrajectoryTurn, ...]
    verdict: JsonObject | None
    cost: CostVector
    parent_episode_id: str | None = None
    execution_digest: str | None = None
    state_digest: str | None = None
    event_range: JsonObject | None = None
    manifest_genome: JsonObject = field(default_factory=dict)
    model_routes_used: tuple[JsonObject, ...] = field(default_factory=tuple)
    verdict_absence_reason: str | None = None
    attribution: JsonObject = field(default_factory=dict)
    outcome: str | None = None

__all__ = [
    "JsonObject",
    "ResourceSelector",
    "Digest",
    "MemoryId",
    "EvaluationRequestId",
    "PreregistrationId",
    "SinkClass",
    "EventKind",
    "GateDecision",
    "ArtifactCreatedPayload",
    "ArtifactIndexEntry",
    "ArtifactRef",
    "Binding",
    "BlobRef",
    "CheckpointPayload",
    "ClaimRef",
    "CompactionReport",
    "ConsolidationReport",
    "ContextBundle",
    "ContextCompactedPayload",
    "EffectContext",
    "EffectFailure",
    "EpisodeOutcome",
    "EpisodeView",
    "EvaluationSubject",
    "EventEnvelope",
    "EventEnvelopeV2",
    "ExecutionProfile",
    "ExecutionProfileV2",
    "GoalDeclaredPayload",
    "Health",
    "MeasurementStatus",
    "MemoryHit",
    "MemoryQuery",
    "MemoryRecord",
    "ModelRoute",
    "OracleSpec",
    "PlanRevisedPayload",
    "PluginRef",
    "ProgressAssessedPayload",
    "ProvenanceClaimPayload",
    "Reflection",
    "Reservation",
    "Selector",
    "SignedVerdict",
    "StrategyChangedPayload",
    "ToolSchema",
    "TrajectoryRef",
    "Capability",
    "Component",
    "CostVector",
    "EffectRequest",
    "FrozenHarness",
    "NamedManifestV2",
    "PluginBindings",
    "Proposal",
    "Receipt",
    "TrajectoryTurn",
    "TrajectoryTurnV2",
    "TrajectoryV2",
    "HarnessManifest",
    "Trajectory",
]
