#!/usr/bin/env python3
"""Generate TypeScript contracts from v4 schemas."""

import argparse
import json
import sys
from pathlib import Path

_TOOLS = Path(__file__).resolve().parent.parent
_COMMON = _TOOLS / "common"
for _path in (_COMMON, _TOOLS):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))

from repo_paths import repo_root

HEADER = '''\
// AUTO-GENERATED by tools/codegen/generate_ts_contracts.py from schemas/v4/
// DO NOT EDIT. Run: python3 tools/codegen/generate_ts_contracts.py

export const SCHEMA_VERSION = "vg.4";

'''

def _load_schemas(schema_dir: Path) -> list[dict]:
    schemas = []
    for path in sorted(schema_dir.glob("*.schema.json")):
        if path.name.endswith(".reader.schema.json"):
            continue
        payload = json.loads(path.read_text(encoding="utf-8"))
        payload["_path"] = path.name
        schemas.append(payload)
    return schemas

def _ts_type(node: dict, is_payload=False) -> str:
    if is_payload:
        return "Readonly<Record<string, unknown> & { kind: string }>"
    
    if "$ref" in node:
        ref = node["$ref"]
        if ".schema.json" in ref and "#" not in ref:
            name = ref.replace(".schema.json", "")
            if name == "model_proposal":
                return "ModelProposal"
            elif name == "worker_protocol":
                return "WorkerProtocol"
            return "".join(p.capitalize() for p in name.split("-"))
            
        name = ref.rsplit("/", 1)[-1]
        if name == "SchemaVersion":
            return "'vg.4'"
        return name
    
    types = node.get("type")
    
    if "anyOf" in node:
        return " | ".join(_ts_type(opt) for opt in node["anyOf"])
    if "allOf" in node:
        pass

    if isinstance(types, list):
        mapped = []
        for t in types:
            if t == "null":
                mapped.append("null")
            else:
                mapped.append(_ts_type({**node, "type": t}))
        return " | ".join(mapped)
        
    if types == "string":
        if "enum" in node:
            return " | ".join(f"'{v}'" for v in node["enum"])
        return "string"
    if types == "integer" or types == "number":
        return "number"
    if types == "boolean":
        return "boolean"
    if types == "array":
        inner = _ts_type(node.get("items", {}))
        if " | " in inner:
            return f"readonly ({inner})[]"
        return f"readonly {inner}[]"
    if types == "object":
        return "Readonly<Record<string, unknown>>"
        
    if "const" in node:
        val = node["const"]
        if isinstance(val, str):
            return f"'{val}'"
        return str(val).lower() if isinstance(val, bool) else str(val)
        
    if "enum" in node:
        return " | ".join(f"'{v}'" for v in node["enum"])
        
    return "unknown"

def _generate_interface(title: str, schema: dict) -> str:
    lines = []
    
    if schema.get("type") == "array":
        items_type = _ts_type(schema.get("items", {}))
        # if items is an object with required/properties, we might need to inline it?
        # For ArtifactKindRegistry it's an object with kind and schema
        if schema.get("items", {}).get("type") == "object":
            req = schema["items"].get("required", [])
            props = schema["items"].get("properties", {})
            lines.append(f"export type {title} = readonly {{")
            for k, v in props.items():
                opt = "?" if k not in req else ""
                lines.append(f"  readonly {k}{opt}: {_ts_type(v)};")
            lines.append("}[];\n")
        else:
            lines.append(f"export type {title} = {items_type};\n")
            
        lines.append(f"export function is{title}(v: unknown): v is {title} {{")
        lines.append(f"  return Array.isArray(v);")
        lines.append("}\n")
        return "\n".join(lines)
        
    req = set(schema.get("required", []))
    props = schema.get("properties", {})
    
    lines.append(f"export interface {title} {{")
    for key, prop in props.items():
        opt = "?" if key not in req else ""
        t = _ts_type(prop, is_payload=(key == "payload" and title == "EventEnvelope"))
        lines.append(f"  readonly {key}{opt}: {t};")
    lines.append("}\n")
    
    lines.append(f"export function is{title}(v: unknown): v is {title} {{")
    lines.append(f"  return typeof v === 'object' && v !== null;")
    lines.append("}\n")
    
    return "\n".join(lines)

def _generate_runtime_service(schema: dict) -> str:
    """Emit the vg.4 RuntimeService frame union and its frozen command tables.

    The generic object emitter cannot express this schema: its root is a
    discriminated ``oneOf`` with no properties of its own, so it produced an
    empty ``RuntimeServiceFrame`` and the seven real fields were hand-edited
    back into the generated file -- a hand-written mirror inside the file that
    bans them (SPEC A-4), which the next codegen run would have silently erased.

    The tables emitted here are the TypeScript half of the same contract
    ``vanguard/packages/runtime/service/contract.py`` states in Python. Both
    are derived from this schema, and
    ``test/contracts/test_runtime_service_contract_parity.py`` proves neither
    has drifted from it.
    """
    defs = schema["$defs"]
    frames = [ref["$ref"].rsplit("/", 1)[-1] for ref in schema["oneOf"]]
    commands = [
        ref["$ref"].rsplit("/", 1)[-1][: -len("Command")]
        for ref in defs["Command"]["oneOf"]
    ]
    lines: list[str] = []

    # Supporting $defs the frame interfaces reference. Without these the
    # generated module does not compile, which is how the hand-edited
    # RuntimeServiceFrame went unnoticed: nothing ever type-checked it.
    lines.append(
        "export type ErrorCode =\n  | "
        + "\n  | ".join(f"'{c}'" for c in defs["ErrorCode"]["enum"])
        + ";\n"
    )
    # ApprovalDecision is deliberately absent: it is a bare $ref to
    # approval-decision.schema.json, which the generic emitter already covers.
    for name in ("ServiceError", "CommandReceipt"):
        lines.append(_generate_interface(name, defs[name]))
    for name in commands:
        lines.append(_generate_interface(name + "Command", defs[name + "Command"]))
    lines.append(
        "export type Command =\n  | "
        + "\n  | ".join(f"{c}Command" for c in commands)
        + ";\n"
    )

    for frame in frames:
        lines.append(_generate_interface(frame, defs[frame]))
    lines.append(
        "export type RuntimeServiceFrame =\n  | "
        + "\n  | ".join(frames)
        + ";\n"
    )
    lines.append("export function isRuntimeServiceFrame(v: unknown): v is RuntimeServiceFrame {")
    lines.append("  return typeof v === 'object' && v !== null;")
    lines.append("}\n")

    lines.append(
        "export type RuntimeServiceCommandName =\n  | "
        + "\n  | ".join(f"'{c}'" for c in commands)
        + ";\n"
    )

    codes = defs["ErrorCode"]["enum"]
    lines.append(
        "export const RUNTIME_SERVICE_ERROR_CODES = [\n"
        + "".join(f"  '{c}',\n" for c in codes)
        + "] as const;\n"
    )

    scope_rows, allowed_rows, required_rows = [], [], []
    for name in commands:
        body = defs[name + "Command"]
        run_id = body["properties"]["runId"]
        if run_id.get("const") == "":
            scope = "forbidden"
        elif "runId" in body.get("required", []):
            scope = "required"
        else:
            scope = "optional"
        scope_rows.append(f"  {name}: '{scope}',")

        payload = body["properties"]["payload"]
        allowed = sorted(payload.get("properties", {}))
        required = list(payload.get("required", []))
        allowed_rows.append(f"  {name}: [{', '.join(repr(f) for f in allowed)}],".replace('"', "'"))
        required_rows.append(f"  {name}: [{', '.join(repr(f) for f in required)}],".replace('"', "'"))

    lines.append(
        "export const RUNTIME_SERVICE_COMMAND_RUN_SCOPE = {\n"
        + "\n".join(scope_rows)
        + "\n} as const;\n"
    )
    lines.append(
        "export const RUNTIME_SERVICE_COMMAND_ALLOWED_PAYLOAD_FIELDS = {\n"
        + "\n".join(allowed_rows)
        + "\n} as const;\n"
    )
    lines.append(
        "export const RUNTIME_SERVICE_COMMAND_REQUIRED_PAYLOAD_FIELDS = {\n"
        + "\n".join(required_rows)
        + "\n} as const;\n"
    )

    seq_fields = sorted(
        {
            field
            for name in commands
            for field, node in defs[name + "Command"]["properties"]["payload"]
            .get("properties", {})
            .items()
            if node.get("$ref") == "#/$defs/SeqGuard"
        }
        | {"afterSeq"}
    )
    lines.append(
        "// Payload fields whose value shape ingress must check, not merely their name:\n"
        "// a JSON integer, or the CT-06 decimal string, because a run sequence may\n"
        "// exceed 2^53-1.\n"
        "export const RUNTIME_SERVICE_SEQ_GUARD_FIELDS = [\n"
        + "".join(f"  '{f}',\n" for f in seq_fields)
        + "] as const;\n"
    )
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    
    root = repo_root()
    schema_dir = root / "schemas" / "v4"
    out_dir = root / "vanguard" / "packages" / "domain" / "generated"
    out_path = out_dir / "contracts.gen.ts"
    index_path = out_dir / "index.ts"
    
    schemas = _load_schemas(schema_dir)
    chunks = [HEADER]
    
    # Process primitives
    prim = next((s for s in schemas if s["_path"] == "primitives.schema.json"), None)
    if prim and "$defs" in prim:
        for name, node in prim["$defs"].items():
            if name == "SchemaVersion":
                continue # Handled by constant
            if "enum" in node:
                vals = " | ".join(f"'{v}'" for v in node["enum"])
                chunks.append(f"export type {name} = {vals};\n")
            else:
                base_type = _ts_type(node)
                if " | " in base_type:
                    base_type = f"({base_type})"
                chunks.append(f"export type {name} = {base_type} & {{ readonly __brand: '{name}' }};\n")
                
    # Process objects
    for s in schemas:
        title = s.get("title")
        if not title or title == "Vanguard v4 primitives":
            continue
        if s["_path"] == "runtime-service.schema.json":
            chunks.append(_generate_runtime_service(s))
            continue
        chunks.append(_generate_interface(title, s))
        
    text = "\n".join(chunks)
    
    if args.check:
        current = out_path.read_text(encoding="utf-8") if out_path.exists() else ""
        if current != text:
            print(f"CODEGEN FAIL: {out_path.relative_to(root)} stale; run tools/codegen/generate_ts_contracts.py")
            return 1
        print("CODEGEN PASS: contracts.gen.ts matches schemas/v4")
        return 0
        
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    
    if not index_path.exists():
        index_path.write_text("export * from './contracts.gen.js';\n", encoding="utf-8")
        
    print(f"wrote {out_path.relative_to(root)}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
