#!/usr/bin/env python3
"""tools/reader_profile.py — derive the reader profile from a writer schema (SC-10).

Writers are strict (04 [CT-11]); readers must preserve unknown fields (04 [CT-44]).
One artifact, two profiles, generated — never two hand-maintained schemas.
"""
import json, sys, copy

def relax(node):
    """Relax strictness AND repoint cross-schema refs at reader profiles.

    Rewriting $id without rewriting $ref silently resolves a reader profile back
    to the writer schema it was derived from, which reinstates the very
    strictness the profile exists to remove. Both must move together.
    """
    if isinstance(node, dict):
        if node.get("additionalProperties") is False:
            node["additionalProperties"] = True
        if isinstance(node.get("$ref"), str) and ".schema.json" in node["$ref"] \
           and ".reader.schema.json" not in node["$ref"]:
            node["$ref"] = node["$ref"].replace(".schema.json", ".reader.schema.json")
        for v in node.values():
            relax(v)
    elif isinstance(node, list):
        for v in node:
            relax(v)
    return node

if __name__ == "__main__":
    for path in sys.argv[1:]:
        d = json.load(open(path))
        r = relax(copy.deepcopy(d))
        r["$id"] = d["$id"].replace(".schema.json", ".reader.schema.json")
        r["$comment"] = "READER PROFILE, generated by tools/reader_profile.py. Do not edit."
        out = path.replace(".schema.json", ".reader.schema.json")
        json.dump(r, open(out, "w"), indent=2)
        print("wrote", out)
