#!/usr/bin/env python3
"""tools/rule_test_map.py — generate docs/v4/rule-test-map.md (CI-9).

A hand-maintained map across ~200 rules rots within a month. This extracts
every rule ID defined in 02-07, joins it against the Guards column of the
must-fail suite in 08 §5, and reports coverage.

Exit 1 when a rule has neither a test nor an untestable marker.
"""
import re, sys, glob, os
from collections import defaultdict

RULE_IN_TABLE = re.compile(r"\|\s*\*{0,2}`?([A-Z]{1,4})-(\d{1,4})`?\*{0,2}\s*\|")
RULE_IN_QUOTE = re.compile(r"^>\s*\*\*`([A-Z]{1,4})-(\d{1,4})`")

def rule_defs(path):
    """Rule IDs DEFINED in a file: first table cell, or a blockquote definition.
    Blockquote definitions were invisible to the first version of this extractor,
    which understated the rule count and produced false dangling references."""
    out = set()
    for line in open(path):
        m = RULE_IN_TABLE.match(line) or RULE_IN_QUOTE.match(line)
        if m:
            out.add((m.group(1), m.group(2)))
    return out


# Rule prefixes that are normative requirements. Excludes descriptive
# taxonomies (FT- failure classes, F- failure paths, T- threats, A-/C-/NC-
# claims and axioms), which are characterisations rather than requirements.
# AT- is deliberately absent: architecture tests ARE tests, not rules needing one.
NORMATIVE = {"N", "CT", "D", "INV", "K", "SA", "MEM", "V", "CL", "M", "LT", "CC"}

# Test families that satisfy CI-9. A must-fail test is the strongest but not the
# only form of evidence; demanding MF coverage for every rule would produce
# ceremonial tests, which is the failure this map exists to prevent.
FAMILIES = {
    "MF":  "must-fail, against a broken implementation",
    "AT":  "architecture test — proves a path does not exist",
    "PT":  "property test — algebraic law",
    "VEC": "conformance vector, cross-language",
    "FI":  "fault injection over 05 §2.3",
}

# Untestable classes, with justification, per 08 §5.1.
UNTESTABLE = {
    "LT": "architectural prohibition — proven by static analysis, stronger than a runtime test",
    "M":  "statistical rule — holds over an experiment family, not one execution; refusal behaviour is separately tested",
    "SA": "human-gated — tested by proving no autonomous code path exists",
}

def rules_defined():
    """Rule IDs defined in a table row of 02-07 (first cell = the ID)."""
    out = {}
    for path in sorted(glob.glob("0[234567]_vanguard_*.md")):
        doc = os.path.basename(path)[:2]
        for pre, num in rule_defs(path):
            if pre in NORMATIVE:
                out[f"{pre}-{num}"] = doc
    return out

def rules_guarded():
    """Rule IDs appearing in the Guards column of the must-fail suite."""
    guarded = defaultdict(list)
    plan = glob.glob("08_vanguard_*.md")
    if not plan:
        return guarded
    for line in open(plan[0]):
        m = re.match(r"\|\s*`(MF-\d+)`\s*\|[^|]*\|([^|]*)\|", line)
        if m:
            for rid in re.findall(r"\[([A-Z]{1,4}-\d{1,4})\]", m.group(2)):
                guarded[rid].append(m.group(1))
    return guarded

def main():
    defined, guarded = rules_defined(), rules_guarded()
    rows, gaps = [], []
    for rid, doc in sorted(defined.items(), key=lambda kv: (kv[1], kv[0])):
        prefix = rid.split("-")[0]
        if rid in guarded:
            rows.append((rid, doc, ", ".join(guarded[rid]), ""))
        elif prefix in UNTESTABLE:
            rows.append((rid, doc, "UNTESTABLE", UNTESTABLE[prefix]))
        else:
            rows.append((rid, doc, "**GAP**", ""))
            gaps.append(rid)

    os.makedirs("docs/v4", exist_ok=True)
    with open("docs/v4/rule-test-map.md", "w") as f:
        f.write("# Rule-to-test map\n\n")
        f.write("Generated by `tools/rule_test_map.py`. Do not edit.\n\n")
        f.write(f"Rules: {len(defined)} · tested: {sum(1 for r in rows if r[2].startswith('MF'))} "
                f"· untestable: {sum(1 for r in rows if r[2]=='UNTESTABLE')} · gaps: {len(gaps)}\n\n")
        f.write("| Rule | Doc | Test | Justification |\n|---|---|---|---|\n")
        for r in rows:
            f.write(f"| `{r[0]}` | {r[1]} | {r[2]} | {r[3]} |\n")

    # Phase 0 implementation backlog (00 §10 / 08 §5.1): uncovered rules with an owner and milestone.
    MILESTONE = {"02":"TK-06","03":"TK-06","04":"TK-01","05":"TK-06","06":"TK-09","07":"TK-12"}
    with open("docs/v4/phase0-rule-backlog.md","w") as f:
        f.write("# Phase 0 rule-coverage backlog\n\nGenerated by `tools/rule_test_map.py`. Do not edit.\n\n")
        f.write("These are **implementation** obligations, not conceptual document defects. "
                "A rule moves off this list only when a test in `08 §5` names it. "
                "Marking one covered without a test is the failure the map exists to prevent.\n\n")
        f.write(f"Open: **{len(gaps)}** of {len(defined)} rules.\n\n")
        f.write("| Rule | Owner doc | Target milestone | Exit gate |\n|---|---|---|---|\n")
        for rid in gaps:
            doc = defined[rid]
            f.write(f"| `{rid}` | {doc} | {MILESTONE.get(doc,'TK-12')} | `CI-9` green at Phase 0 exit |\n")

    print(f"rules={len(defined)} tested={sum(1 for r in rows if r[2].startswith('MF'))} "
          f"untestable={sum(1 for r in rows if r[2]=='UNTESTABLE')} gaps={len(gaps)}")
    if gaps:
        print("GAP:", ", ".join(gaps[:40]) + (" ..." if len(gaps) > 40 else ""))
    return 1 if gaps else 0

if __name__ == "__main__":
    sys.exit(main())
